name: Docker Build & Publish

on:
  push:
    branches: [production]

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/{buecherworm}:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/{buecherworm}:latest
          secrets: |
            NEXT_APPWRITE_KEY=${{ secrets.APPWRITE_KEY }}
            NEXT_PUBLIC_APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }}
            NEXT_PUBLIC_APPWRITE_PROJECT=${{ secrets.APPWRITE_PROJECT }}
            NEXT_PUBLIC_DATABASE=${{ secrets.DATABASE }}
            NEXT_PUBLIC_BOOK_IMAGE_BUCKET=${{ secrets.BOOK_IMAGE_BUCKET }}